<?xml version="1.0" encoding="utf-8"?>

<Project>
  <PropertyGroup>
    <PackageVersion>$(Version)$(VersionSuffix)</PackageVersion>
    <PackageIcon>images\icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/DragoAnt/SerilogSinksInMemory/</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/DragoAnt/SerilogSinksInMemory/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>package.readme.md</PackageReadmeFile>
  </PropertyGroup>
</Project>